# Generated by Django 4.2.7 on 2025-11-03 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='词条标题')),
                ('content', models.TextField(verbose_name='词条内容')),
                ('category', models.CharField(max_length=50, verbose_name='词条分类')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '百科词条',
                'verbose_name_plural': '百科词条',
                'ordering': ['-update_time'],
            },
        ),
    ]
